---
abstract: 'a bridge that supports EV from POE'
author:
  - 'Andy Grundman <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  POE::Test::Loops: '1.360'
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: 6.36
  POE::Test::Loops: '1.360'
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Loop-EV
no_index:
  directory:
    - inc
    - t
provides:
  POE::Loop::EV:
    file: lib/POE/Loop/EV.pm
    version: '0.11'
requires:
  EV: '4.0'
  POE: '1.366'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Grinnz/POE-Loop-EV
version: '0.11'
