--- 
abstract: a bridge that supports EV from POE
author: Andy Grundman <andy@hybridized.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Loop-EV
no_index: 
  directory: 
    - inc
    - t
provides: 
  POE::Loop::EV: 
    file: lib/POE/Loop/EV.pm
    version: 0.06
requires: 
  EV: 3.0
  POE: 0.9999
  Test::More: 0.47
tests: t/*.t t/*/*/*.t
version: 0.06
